// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: smallbiznis/webhook/v1/webhook.proto

package webhookv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WebhookService_CreateWebhookSubscription_FullMethodName = "/smallbiznis.webhook.v1.WebhookService/CreateWebhookSubscription"
	WebhookService_ListWebhookSubscriptions_FullMethodName  = "/smallbiznis.webhook.v1.WebhookService/ListWebhookSubscriptions"
	WebhookService_DeleteWebhookSubscription_FullMethodName = "/smallbiznis.webhook.v1.WebhookService/DeleteWebhookSubscription"
	WebhookService_TriggerWebhook_FullMethodName            = "/smallbiznis.webhook.v1.WebhookService/TriggerWebhook"
	WebhookService_ListWebhookDeliveries_FullMethodName     = "/smallbiznis.webhook.v1.WebhookService/ListWebhookDeliveries"
)

// WebhookServiceClient is the client API for WebhookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebhookServiceClient interface {
	CreateWebhookSubscription(ctx context.Context, in *CreateWebhookSubscriptionRequest, opts ...grpc.CallOption) (*CreateWebhookSubscriptionResponse, error)
	ListWebhookSubscriptions(ctx context.Context, in *ListWebhookSubscriptionsRequest, opts ...grpc.CallOption) (*ListWebhookSubscriptionsResponse, error)
	DeleteWebhookSubscription(ctx context.Context, in *DeleteWebhookSubscriptionRequest, opts ...grpc.CallOption) (*DeleteWebhookSubscriptionResponse, error)
	// Called by internal services to queue webhook delivery
	TriggerWebhook(ctx context.Context, in *TriggerWebhookRequest, opts ...grpc.CallOption) (*TriggerWebhookResponse, error)
	// For console UI to view logs
	ListWebhookDeliveries(ctx context.Context, in *ListWebhookDeliveriesRequest, opts ...grpc.CallOption) (*ListWebhookDeliveriesResponse, error)
}

type webhookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebhookServiceClient(cc grpc.ClientConnInterface) WebhookServiceClient {
	return &webhookServiceClient{cc}
}

func (c *webhookServiceClient) CreateWebhookSubscription(ctx context.Context, in *CreateWebhookSubscriptionRequest, opts ...grpc.CallOption) (*CreateWebhookSubscriptionResponse, error) {
	out := new(CreateWebhookSubscriptionResponse)
	err := c.cc.Invoke(ctx, WebhookService_CreateWebhookSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) ListWebhookSubscriptions(ctx context.Context, in *ListWebhookSubscriptionsRequest, opts ...grpc.CallOption) (*ListWebhookSubscriptionsResponse, error) {
	out := new(ListWebhookSubscriptionsResponse)
	err := c.cc.Invoke(ctx, WebhookService_ListWebhookSubscriptions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) DeleteWebhookSubscription(ctx context.Context, in *DeleteWebhookSubscriptionRequest, opts ...grpc.CallOption) (*DeleteWebhookSubscriptionResponse, error) {
	out := new(DeleteWebhookSubscriptionResponse)
	err := c.cc.Invoke(ctx, WebhookService_DeleteWebhookSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) TriggerWebhook(ctx context.Context, in *TriggerWebhookRequest, opts ...grpc.CallOption) (*TriggerWebhookResponse, error) {
	out := new(TriggerWebhookResponse)
	err := c.cc.Invoke(ctx, WebhookService_TriggerWebhook_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) ListWebhookDeliveries(ctx context.Context, in *ListWebhookDeliveriesRequest, opts ...grpc.CallOption) (*ListWebhookDeliveriesResponse, error) {
	out := new(ListWebhookDeliveriesResponse)
	err := c.cc.Invoke(ctx, WebhookService_ListWebhookDeliveries_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebhookServiceServer is the server API for WebhookService service.
// All implementations must embed UnimplementedWebhookServiceServer
// for forward compatibility
type WebhookServiceServer interface {
	CreateWebhookSubscription(context.Context, *CreateWebhookSubscriptionRequest) (*CreateWebhookSubscriptionResponse, error)
	ListWebhookSubscriptions(context.Context, *ListWebhookSubscriptionsRequest) (*ListWebhookSubscriptionsResponse, error)
	DeleteWebhookSubscription(context.Context, *DeleteWebhookSubscriptionRequest) (*DeleteWebhookSubscriptionResponse, error)
	// Called by internal services to queue webhook delivery
	TriggerWebhook(context.Context, *TriggerWebhookRequest) (*TriggerWebhookResponse, error)
	// For console UI to view logs
	ListWebhookDeliveries(context.Context, *ListWebhookDeliveriesRequest) (*ListWebhookDeliveriesResponse, error)
	mustEmbedUnimplementedWebhookServiceServer()
}

// UnimplementedWebhookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWebhookServiceServer struct {
}

func (UnimplementedWebhookServiceServer) CreateWebhookSubscription(context.Context, *CreateWebhookSubscriptionRequest) (*CreateWebhookSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWebhookSubscription not implemented")
}
func (UnimplementedWebhookServiceServer) ListWebhookSubscriptions(context.Context, *ListWebhookSubscriptionsRequest) (*ListWebhookSubscriptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWebhookSubscriptions not implemented")
}
func (UnimplementedWebhookServiceServer) DeleteWebhookSubscription(context.Context, *DeleteWebhookSubscriptionRequest) (*DeleteWebhookSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWebhookSubscription not implemented")
}
func (UnimplementedWebhookServiceServer) TriggerWebhook(context.Context, *TriggerWebhookRequest) (*TriggerWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerWebhook not implemented")
}
func (UnimplementedWebhookServiceServer) ListWebhookDeliveries(context.Context, *ListWebhookDeliveriesRequest) (*ListWebhookDeliveriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWebhookDeliveries not implemented")
}
func (UnimplementedWebhookServiceServer) mustEmbedUnimplementedWebhookServiceServer() {}

// UnsafeWebhookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebhookServiceServer will
// result in compilation errors.
type UnsafeWebhookServiceServer interface {
	mustEmbedUnimplementedWebhookServiceServer()
}

func RegisterWebhookServiceServer(s grpc.ServiceRegistrar, srv WebhookServiceServer) {
	s.RegisterService(&WebhookService_ServiceDesc, srv)
}

func _WebhookService_CreateWebhookSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWebhookSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).CreateWebhookSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_CreateWebhookSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).CreateWebhookSubscription(ctx, req.(*CreateWebhookSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_ListWebhookSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebhookSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).ListWebhookSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_ListWebhookSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).ListWebhookSubscriptions(ctx, req.(*ListWebhookSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_DeleteWebhookSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWebhookSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).DeleteWebhookSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_DeleteWebhookSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).DeleteWebhookSubscription(ctx, req.(*DeleteWebhookSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_TriggerWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).TriggerWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_TriggerWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).TriggerWebhook(ctx, req.(*TriggerWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_ListWebhookDeliveries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebhookDeliveriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).ListWebhookDeliveries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_ListWebhookDeliveries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).ListWebhookDeliveries(ctx, req.(*ListWebhookDeliveriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebhookService_ServiceDesc is the grpc.ServiceDesc for WebhookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebhookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smallbiznis.webhook.v1.WebhookService",
	HandlerType: (*WebhookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWebhookSubscription",
			Handler:    _WebhookService_CreateWebhookSubscription_Handler,
		},
		{
			MethodName: "ListWebhookSubscriptions",
			Handler:    _WebhookService_ListWebhookSubscriptions_Handler,
		},
		{
			MethodName: "DeleteWebhookSubscription",
			Handler:    _WebhookService_DeleteWebhookSubscription_Handler,
		},
		{
			MethodName: "TriggerWebhook",
			Handler:    _WebhookService_TriggerWebhook_Handler,
		},
		{
			MethodName: "ListWebhookDeliveries",
			Handler:    _WebhookService_ListWebhookDeliveries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smallbiznis/webhook/v1/webhook.proto",
}
