// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: smallbiznis/invoice_engine/v1/invoice_engine.proto

package invoiceenginev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InvoiceEngineService_GenerateInvoice_FullMethodName = "/smallbiznis.invoice_engine.v1.InvoiceEngineService/GenerateInvoice"
)

// InvoiceEngineServiceClient is the client API for InvoiceEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvoiceEngineServiceClient interface {
	// Generate an invoice for the given subscription and billing window.
	GenerateInvoice(ctx context.Context, in *GenerateInvoiceRequest, opts ...grpc.CallOption) (*GenerateInvoiceResponse, error)
}

type invoiceEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInvoiceEngineServiceClient(cc grpc.ClientConnInterface) InvoiceEngineServiceClient {
	return &invoiceEngineServiceClient{cc}
}

func (c *invoiceEngineServiceClient) GenerateInvoice(ctx context.Context, in *GenerateInvoiceRequest, opts ...grpc.CallOption) (*GenerateInvoiceResponse, error) {
	out := new(GenerateInvoiceResponse)
	err := c.cc.Invoke(ctx, InvoiceEngineService_GenerateInvoice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvoiceEngineServiceServer is the server API for InvoiceEngineService service.
// All implementations must embed UnimplementedInvoiceEngineServiceServer
// for forward compatibility
type InvoiceEngineServiceServer interface {
	// Generate an invoice for the given subscription and billing window.
	GenerateInvoice(context.Context, *GenerateInvoiceRequest) (*GenerateInvoiceResponse, error)
	mustEmbedUnimplementedInvoiceEngineServiceServer()
}

// UnimplementedInvoiceEngineServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInvoiceEngineServiceServer struct {
}

func (UnimplementedInvoiceEngineServiceServer) GenerateInvoice(context.Context, *GenerateInvoiceRequest) (*GenerateInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateInvoice not implemented")
}
func (UnimplementedInvoiceEngineServiceServer) mustEmbedUnimplementedInvoiceEngineServiceServer() {}

// UnsafeInvoiceEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvoiceEngineServiceServer will
// result in compilation errors.
type UnsafeInvoiceEngineServiceServer interface {
	mustEmbedUnimplementedInvoiceEngineServiceServer()
}

func RegisterInvoiceEngineServiceServer(s grpc.ServiceRegistrar, srv InvoiceEngineServiceServer) {
	s.RegisterService(&InvoiceEngineService_ServiceDesc, srv)
}

func _InvoiceEngineService_GenerateInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceEngineServiceServer).GenerateInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoiceEngineService_GenerateInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceEngineServiceServer).GenerateInvoice(ctx, req.(*GenerateInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InvoiceEngineService_ServiceDesc is the grpc.ServiceDesc for InvoiceEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvoiceEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smallbiznis.invoice_engine.v1.InvoiceEngineService",
	HandlerType: (*InvoiceEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateInvoice",
			Handler:    _InvoiceEngineService_GenerateInvoice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smallbiznis/invoice_engine/v1/invoice_engine.proto",
}
