// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: smallbiznis/pricing/v1/pricing.proto

package pricingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PricingService_CreateProduct_FullMethodName    = "/smallbiznis.pricing.v1.PricingService/CreateProduct"
	PricingService_GetProduct_FullMethodName       = "/smallbiznis.pricing.v1.PricingService/GetProduct"
	PricingService_ListProducts_FullMethodName     = "/smallbiznis.pricing.v1.PricingService/ListProducts"
	PricingService_CreatePrice_FullMethodName      = "/smallbiznis.pricing.v1.PricingService/CreatePrice"
	PricingService_GetPrice_FullMethodName         = "/smallbiznis.pricing.v1.PricingService/GetPrice"
	PricingService_ListPrices_FullMethodName       = "/smallbiznis.pricing.v1.PricingService/ListPrices"
	PricingService_ListPriceTiers_FullMethodName   = "/smallbiznis.pricing.v1.PricingService/ListPriceTiers"
	PricingService_ListPriceAmounts_FullMethodName = "/smallbiznis.pricing.v1.PricingService/ListPriceAmounts"
)

// PricingServiceClient is the client API for PricingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PricingServiceClient interface {
	// Create a new product definition for a tenant.
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*Product, error)
	// Retrieve a product by ID within a tenant.
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*Product, error)
	// List products for a tenant with pagination.
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
	// Create a price (and optional tiers) for a product.
	CreatePrice(ctx context.Context, in *CreatePriceRequest, opts ...grpc.CallOption) (*Price, error)
	// Retrieve a price by ID within a tenant.
	GetPrice(ctx context.Context, in *GetPriceRequest, opts ...grpc.CallOption) (*Price, error)
	// List prices filtered by tenant/product/code with pagination. Tiers are
	// returned alongside their parent prices.
	ListPrices(ctx context.Context, in *ListPricesRequest, opts ...grpc.CallOption) (*ListPricesResponse, error)
	// List tiers for prices within a tenant context.
	ListPriceTiers(ctx context.Context, in *ListPriceTiersRequest, opts ...grpc.CallOption) (*ListPriceTiersResponse, error)
	// List currency-specific amounts for prices within a tenant context.
	ListPriceAmounts(ctx context.Context, in *ListPriceAmountsRequest, opts ...grpc.CallOption) (*ListPriceAmountsResponse, error)
}

type pricingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPricingServiceClient(cc grpc.ClientConnInterface) PricingServiceClient {
	return &pricingServiceClient{cc}
}

func (c *pricingServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, PricingService_CreateProduct_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pricingServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, PricingService_GetProduct_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pricingServiceClient) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, PricingService_ListProducts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pricingServiceClient) CreatePrice(ctx context.Context, in *CreatePriceRequest, opts ...grpc.CallOption) (*Price, error) {
	out := new(Price)
	err := c.cc.Invoke(ctx, PricingService_CreatePrice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pricingServiceClient) GetPrice(ctx context.Context, in *GetPriceRequest, opts ...grpc.CallOption) (*Price, error) {
	out := new(Price)
	err := c.cc.Invoke(ctx, PricingService_GetPrice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pricingServiceClient) ListPrices(ctx context.Context, in *ListPricesRequest, opts ...grpc.CallOption) (*ListPricesResponse, error) {
	out := new(ListPricesResponse)
	err := c.cc.Invoke(ctx, PricingService_ListPrices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pricingServiceClient) ListPriceTiers(ctx context.Context, in *ListPriceTiersRequest, opts ...grpc.CallOption) (*ListPriceTiersResponse, error) {
	out := new(ListPriceTiersResponse)
	err := c.cc.Invoke(ctx, PricingService_ListPriceTiers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pricingServiceClient) ListPriceAmounts(ctx context.Context, in *ListPriceAmountsRequest, opts ...grpc.CallOption) (*ListPriceAmountsResponse, error) {
	out := new(ListPriceAmountsResponse)
	err := c.cc.Invoke(ctx, PricingService_ListPriceAmounts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PricingServiceServer is the server API for PricingService service.
// All implementations must embed UnimplementedPricingServiceServer
// for forward compatibility
type PricingServiceServer interface {
	// Create a new product definition for a tenant.
	CreateProduct(context.Context, *CreateProductRequest) (*Product, error)
	// Retrieve a product by ID within a tenant.
	GetProduct(context.Context, *GetProductRequest) (*Product, error)
	// List products for a tenant with pagination.
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error)
	// Create a price (and optional tiers) for a product.
	CreatePrice(context.Context, *CreatePriceRequest) (*Price, error)
	// Retrieve a price by ID within a tenant.
	GetPrice(context.Context, *GetPriceRequest) (*Price, error)
	// List prices filtered by tenant/product/code with pagination. Tiers are
	// returned alongside their parent prices.
	ListPrices(context.Context, *ListPricesRequest) (*ListPricesResponse, error)
	// List tiers for prices within a tenant context.
	ListPriceTiers(context.Context, *ListPriceTiersRequest) (*ListPriceTiersResponse, error)
	// List currency-specific amounts for prices within a tenant context.
	ListPriceAmounts(context.Context, *ListPriceAmountsRequest) (*ListPriceAmountsResponse, error)
	mustEmbedUnimplementedPricingServiceServer()
}

// UnimplementedPricingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPricingServiceServer struct {
}

func (UnimplementedPricingServiceServer) CreateProduct(context.Context, *CreateProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedPricingServiceServer) GetProduct(context.Context, *GetProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedPricingServiceServer) ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedPricingServiceServer) CreatePrice(context.Context, *CreatePriceRequest) (*Price, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePrice not implemented")
}
func (UnimplementedPricingServiceServer) GetPrice(context.Context, *GetPriceRequest) (*Price, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrice not implemented")
}
func (UnimplementedPricingServiceServer) ListPrices(context.Context, *ListPricesRequest) (*ListPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPrices not implemented")
}
func (UnimplementedPricingServiceServer) ListPriceTiers(context.Context, *ListPriceTiersRequest) (*ListPriceTiersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPriceTiers not implemented")
}
func (UnimplementedPricingServiceServer) ListPriceAmounts(context.Context, *ListPriceAmountsRequest) (*ListPriceAmountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPriceAmounts not implemented")
}
func (UnimplementedPricingServiceServer) mustEmbedUnimplementedPricingServiceServer() {}

// UnsafePricingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PricingServiceServer will
// result in compilation errors.
type UnsafePricingServiceServer interface {
	mustEmbedUnimplementedPricingServiceServer()
}

func RegisterPricingServiceServer(s grpc.ServiceRegistrar, srv PricingServiceServer) {
	s.RegisterService(&PricingService_ServiceDesc, srv)
}

func _PricingService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PricingService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PricingService_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_ListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).ListProducts(ctx, req.(*ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PricingService_CreatePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).CreatePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_CreatePrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).CreatePrice(ctx, req.(*CreatePriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PricingService_GetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).GetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_GetPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).GetPrice(ctx, req.(*GetPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PricingService_ListPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).ListPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_ListPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).ListPrices(ctx, req.(*ListPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PricingService_ListPriceTiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPriceTiersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).ListPriceTiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_ListPriceTiers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).ListPriceTiers(ctx, req.(*ListPriceTiersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PricingService_ListPriceAmounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPriceAmountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).ListPriceAmounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_ListPriceAmounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).ListPriceAmounts(ctx, req.(*ListPriceAmountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PricingService_ServiceDesc is the grpc.ServiceDesc for PricingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PricingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smallbiznis.pricing.v1.PricingService",
	HandlerType: (*PricingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _PricingService_CreateProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _PricingService_GetProduct_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _PricingService_ListProducts_Handler,
		},
		{
			MethodName: "CreatePrice",
			Handler:    _PricingService_CreatePrice_Handler,
		},
		{
			MethodName: "GetPrice",
			Handler:    _PricingService_GetPrice_Handler,
		},
		{
			MethodName: "ListPrices",
			Handler:    _PricingService_ListPrices_Handler,
		},
		{
			MethodName: "ListPriceTiers",
			Handler:    _PricingService_ListPriceTiers_Handler,
		},
		{
			MethodName: "ListPriceAmounts",
			Handler:    _PricingService_ListPriceAmounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smallbiznis/pricing/v1/pricing.proto",
}
