// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: smallbiznis/subdomain/v1/subdomain.proto

package subdomainv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SubdomainService_CreateSubdomain_FullMethodName = "/smallbiznis.subdomain.v1.SubdomainService/CreateSubdomain"
	SubdomainService_GetSubdomain_FullMethodName    = "/smallbiznis.subdomain.v1.SubdomainService/GetSubdomain"
	SubdomainService_ListSubdomains_FullMethodName  = "/smallbiznis.subdomain.v1.SubdomainService/ListSubdomains"
	SubdomainService_UpdateSubdomain_FullMethodName = "/smallbiznis.subdomain.v1.SubdomainService/UpdateSubdomain"
)

// SubdomainServiceClient is the client API for SubdomainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubdomainServiceClient interface {
	CreateSubdomain(ctx context.Context, in *CreateSubdomainRequest, opts ...grpc.CallOption) (*Domain, error)
	GetSubdomain(ctx context.Context, in *GetSubdomainRequest, opts ...grpc.CallOption) (*Domain, error)
	ListSubdomains(ctx context.Context, in *ListSubdomainsRequest, opts ...grpc.CallOption) (*ListSubdomainsResponse, error)
	UpdateSubdomain(ctx context.Context, in *UpdateSubdomainRequest, opts ...grpc.CallOption) (*Domain, error)
}

type subdomainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubdomainServiceClient(cc grpc.ClientConnInterface) SubdomainServiceClient {
	return &subdomainServiceClient{cc}
}

func (c *subdomainServiceClient) CreateSubdomain(ctx context.Context, in *CreateSubdomainRequest, opts ...grpc.CallOption) (*Domain, error) {
	out := new(Domain)
	err := c.cc.Invoke(ctx, SubdomainService_CreateSubdomain_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subdomainServiceClient) GetSubdomain(ctx context.Context, in *GetSubdomainRequest, opts ...grpc.CallOption) (*Domain, error) {
	out := new(Domain)
	err := c.cc.Invoke(ctx, SubdomainService_GetSubdomain_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subdomainServiceClient) ListSubdomains(ctx context.Context, in *ListSubdomainsRequest, opts ...grpc.CallOption) (*ListSubdomainsResponse, error) {
	out := new(ListSubdomainsResponse)
	err := c.cc.Invoke(ctx, SubdomainService_ListSubdomains_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subdomainServiceClient) UpdateSubdomain(ctx context.Context, in *UpdateSubdomainRequest, opts ...grpc.CallOption) (*Domain, error) {
	out := new(Domain)
	err := c.cc.Invoke(ctx, SubdomainService_UpdateSubdomain_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubdomainServiceServer is the server API for SubdomainService service.
// All implementations must embed UnimplementedSubdomainServiceServer
// for forward compatibility
type SubdomainServiceServer interface {
	CreateSubdomain(context.Context, *CreateSubdomainRequest) (*Domain, error)
	GetSubdomain(context.Context, *GetSubdomainRequest) (*Domain, error)
	ListSubdomains(context.Context, *ListSubdomainsRequest) (*ListSubdomainsResponse, error)
	UpdateSubdomain(context.Context, *UpdateSubdomainRequest) (*Domain, error)
	mustEmbedUnimplementedSubdomainServiceServer()
}

// UnimplementedSubdomainServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSubdomainServiceServer struct {
}

func (UnimplementedSubdomainServiceServer) CreateSubdomain(context.Context, *CreateSubdomainRequest) (*Domain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubdomain not implemented")
}
func (UnimplementedSubdomainServiceServer) GetSubdomain(context.Context, *GetSubdomainRequest) (*Domain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubdomain not implemented")
}
func (UnimplementedSubdomainServiceServer) ListSubdomains(context.Context, *ListSubdomainsRequest) (*ListSubdomainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSubdomains not implemented")
}
func (UnimplementedSubdomainServiceServer) UpdateSubdomain(context.Context, *UpdateSubdomainRequest) (*Domain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubdomain not implemented")
}
func (UnimplementedSubdomainServiceServer) mustEmbedUnimplementedSubdomainServiceServer() {}

// UnsafeSubdomainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubdomainServiceServer will
// result in compilation errors.
type UnsafeSubdomainServiceServer interface {
	mustEmbedUnimplementedSubdomainServiceServer()
}

func RegisterSubdomainServiceServer(s grpc.ServiceRegistrar, srv SubdomainServiceServer) {
	s.RegisterService(&SubdomainService_ServiceDesc, srv)
}

func _SubdomainService_CreateSubdomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubdomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubdomainServiceServer).CreateSubdomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubdomainService_CreateSubdomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubdomainServiceServer).CreateSubdomain(ctx, req.(*CreateSubdomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubdomainService_GetSubdomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubdomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubdomainServiceServer).GetSubdomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubdomainService_GetSubdomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubdomainServiceServer).GetSubdomain(ctx, req.(*GetSubdomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubdomainService_ListSubdomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubdomainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubdomainServiceServer).ListSubdomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubdomainService_ListSubdomains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubdomainServiceServer).ListSubdomains(ctx, req.(*ListSubdomainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubdomainService_UpdateSubdomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubdomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubdomainServiceServer).UpdateSubdomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubdomainService_UpdateSubdomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubdomainServiceServer).UpdateSubdomain(ctx, req.(*UpdateSubdomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubdomainService_ServiceDesc is the grpc.ServiceDesc for SubdomainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubdomainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smallbiznis.subdomain.v1.SubdomainService",
	HandlerType: (*SubdomainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSubdomain",
			Handler:    _SubdomainService_CreateSubdomain_Handler,
		},
		{
			MethodName: "GetSubdomain",
			Handler:    _SubdomainService_GetSubdomain_Handler,
		},
		{
			MethodName: "ListSubdomains",
			Handler:    _SubdomainService_ListSubdomains_Handler,
		},
		{
			MethodName: "UpdateSubdomain",
			Handler:    _SubdomainService_UpdateSubdomain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smallbiznis/subdomain/v1/subdomain.proto",
}
