// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: smallbiznis/event/v1/event_catalog.proto

package eventv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EventCatalogService_ListEvents_FullMethodName = "/smallbiznis.event.v1.EventCatalogService/ListEvents"
)

// EventCatalogServiceClient is the client API for EventCatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventCatalogServiceClient interface {
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*EventCatalog, error)
}

type eventCatalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventCatalogServiceClient(cc grpc.ClientConnInterface) EventCatalogServiceClient {
	return &eventCatalogServiceClient{cc}
}

func (c *eventCatalogServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*EventCatalog, error) {
	out := new(EventCatalog)
	err := c.cc.Invoke(ctx, EventCatalogService_ListEvents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventCatalogServiceServer is the server API for EventCatalogService service.
// All implementations must embed UnimplementedEventCatalogServiceServer
// for forward compatibility
type EventCatalogServiceServer interface {
	ListEvents(context.Context, *ListEventsRequest) (*EventCatalog, error)
	mustEmbedUnimplementedEventCatalogServiceServer()
}

// UnimplementedEventCatalogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEventCatalogServiceServer struct {
}

func (UnimplementedEventCatalogServiceServer) ListEvents(context.Context, *ListEventsRequest) (*EventCatalog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedEventCatalogServiceServer) mustEmbedUnimplementedEventCatalogServiceServer() {}

// UnsafeEventCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventCatalogServiceServer will
// result in compilation errors.
type UnsafeEventCatalogServiceServer interface {
	mustEmbedUnimplementedEventCatalogServiceServer()
}

func RegisterEventCatalogServiceServer(s grpc.ServiceRegistrar, srv EventCatalogServiceServer) {
	s.RegisterService(&EventCatalogService_ServiceDesc, srv)
}

func _EventCatalogService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCatalogServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCatalogService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCatalogServiceServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventCatalogService_ServiceDesc is the grpc.ServiceDesc for EventCatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventCatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smallbiznis.event.v1.EventCatalogService",
	HandlerType: (*EventCatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEvents",
			Handler:    _EventCatalogService_ListEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smallbiznis/event/v1/event_catalog.proto",
}
